[project]
profile = default

[default]
dockerfile = .dex/cmake.Dockerfile

[alias:configure]
desc = Run configure.
cmd = cmake -S ${SOURCE_DIR} -B ${BUILD_DIR} -G Ninja
env = SOURCE_DIR=.,BUILD_DIR=./build
user = $(id -u):$(id -g)

[alias:build]
desc = Run build.
cmd = cmake --build ${BUILD_DIR} --target all -j$JOBS
env = BUILD_DIR=./build,JOBS=$(nproc)
user = $(id -u):$(id -g)

[alias:test]
desc = Run tests.
cmd = cmake --build ${BUILD_DIR} --target test -j$JOBS
env = BUILD_DIR=./build
user = $(id -u):$(id -g)

[alias:clean]
desc = Clean build directory.
cmd = rm -rf ${BUILD_DIR}
env = BUILD_DIR=./build

[alias:execute]
desc = Clean build directory.
cmd = ${BUILD_DIR}/expression-main
env = BUILD_DIR=./build
user = $(id -u):$(id -g)
interactive = true

[alias:run]
desc = Run executable.
pipeline = configure,build,execute

[alias:ci]
desc = Run pipeline.
pipeline = configure,build,test
